#!/usr/bin/env python3
"""Bundle each ``openapi-<domain>.json`` selector into one self-contained OpenAPI document.

For each selector at the repo root this writes ``dist/openapi-<domain>-bundled.json``:
a document whose ``components.schemas`` holds every schema the selector reaches, with
every reference rewritten to point inside the document.

Why this exists
---------------
The Julia model packages are generated by OpenAPI.jl's native generator. It resolves
cross-file ``$ref`` values on its own, but it resolves ``discriminator.mapping`` values
only inside a single document, so a multi-file schema tree cannot be fed to it directly.
This script produces that single document and does nothing else: it moves schemas, it
does not reshape them.

Rules
-----
* ``components.schemas`` holds each reachable schema exactly once, under one name: the
  selector's key for anything the selector publishes, the ``$defs`` key for a definition
  the walk reaches, or the file stem for a whole-file schema the walk reaches.
* Every ``$ref``, external or internal, becomes ``#/components/schemas/<name>``. Keys
  beside a ``$ref`` stay where they are: under OpenAPI 3.1 they apply, and both generators
  honor them.
* ``discriminator.mapping`` and ``defaultMapping`` values are references resolved
  relative to the file that contains them, exactly like ``$ref``, and rewritten the same
  way.
* No root ``$defs`` (OpenAPI.jl rejects it) and no inlining. Two distinct schemas
  claiming one name is an error.

Determinism
-----------
Selector entries come first, in selector order, followed by the definitions the walk
pulled in, sorted by name. ``json.dump`` runs with ``ensure_ascii=False`` and a trailing
newline, so identical inputs give identical bytes, which ``--check`` relies on.

Usage
-----
    python scripts/bundle_specs.py            # write dist/*-bundled.json
    python scripts/bundle_specs.py --check    # exit non-zero if dist/ is stale

Stdlib only.
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DIST_DIR = REPO_ROOT / "dist"
DOMAINS = [
    "infrastructure-core",
    "core",
    "operations",
    "investments",
    "dynamics",
    "timeseries",
]

# Shared across all domain bundles: common.json (and any multiply-$ref'd file) is
# parsed from disk once. Keyed by resolved absolute path.
_file_cache = {}


def load_json(path):
    key = str(Path(path).resolve())
    if key not in _file_cache:
        with open(path) as fh:
            _file_cache[key] = json.load(fh)
    return _file_cache[key]


def split_ref(ref):
    """Split a $ref into (filepart, fragment). filepart '' means same document."""
    if "#" in ref:
        filepart, fragment = ref.split("#", 1)
    else:
        filepart, fragment = ref, ""
    return filepart, fragment


def is_external(ref):
    filepart, _ = split_ref(ref)
    return filepart != ""


def resolve_fragment(doc, fragment):
    """Follow a JSON-pointer fragment (leading '/') into doc."""
    node = doc
    if fragment in ("", "/"):
        return node
    for token in fragment.strip("/").split("/"):
        token = token.replace("~1", "/").replace("~0", "~")
        if isinstance(node, dict) and token in node:
            node = node[token]
        else:
            raise KeyError(f"fragment token '{token}' not found in {fragment}")
    return node


class BundleError(ValueError):
    """A selector or schema shape the bundler refuses to guess about."""


def resolve_ref_path(base_path, ref):
    """Split a reference into (file, fragment), the file part resolved relative to
    the document carrying it. `$ref` and discriminator mapping values resolve the
    same way, so both go through here -- and so does check_refs.py's gate."""
    filepart, fragment = split_ref(ref)
    path = (base_path.parent / filepart).resolve() if filepart else base_path
    if fragment == "/":
        fragment = ""
    if fragment and not fragment.startswith("/"):
        raise BundleError(f"{base_path.name}: unsupported reference {ref!r}")
    if not path.is_file():
        raise BundleError(f"{base_path.name}: {ref!r} names a missing file")
    return (path, fragment)


class Bundler:
    """Bundles one selector. A *target* is ``(resolved file path, fragment)``; the
    fragment is ``''`` for a whole file or ``/$defs/<Name>`` for a definition."""

    def __init__(self, spec_path):
        self.spec_path = Path(spec_path).resolve()
        self.spec = load_json(self.spec_path)
        self.names = {}  # target -> name
        self.targets = {}  # name -> target
        self.bodies = {}  # name -> rewritten body
        self.pending = []  # names whose body has not been rewritten yet

    def bundle(self):
        schemas = self.spec.get("components", {}).get("schemas", {})
        order = []
        for name, entry in schemas.items():
            if not (
                isinstance(entry, dict)
                and set(entry) == {"$ref"}
                and is_external(entry["$ref"])
            ):
                raise BundleError(
                    f"{self.spec_path.name}: components.schemas.{name} must be a bare "
                    "external $ref; the selector only selects, it does not define"
                )
            self._assign(resolve_ref_path(self.spec_path, entry["$ref"]), name)
            order.append(name)
        while self.pending:
            name = self.pending.pop(0)
            path, fragment = self.targets[name]
            body = resolve_fragment(load_json(path), fragment)
            self.bodies[name] = self._rewrite(body, path)
        published = set(order)
        extras = sorted(name for name in self.bodies if name not in published)

        components = dict(self.spec.get("components", {}))
        components["schemas"] = {name: self.bodies[name] for name in order + extras}
        return {
            key: (components if key == "components" else value)
            for key, value in self.spec.items()
        }

    def _default_name(self, target):
        path, fragment = target
        if fragment == "":
            return path.stem
        tokens = fragment.strip("/").split("/")
        if len(tokens) == 2 and tokens[0] == "$defs":
            return tokens[1]
        raise BundleError(
            f"{path.name}#{fragment}: only whole-file schemas and $defs entries can be "
            "bundled as components"
        )

    def _assign(self, target, name=None):
        """Give `target` a component name (the selector's, or a default) and queue it."""
        existing = self.names.get(target)
        if existing is not None:
            if name is not None and name != existing:
                raise BundleError(
                    f"{self.spec_path.name}: {target[0].name}#{target[1]} is published as "
                    f"both {existing!r} and {name!r}"
                )
            return existing
        if name is None:
            name = self._default_name(target)
        other = self.targets.get(name)
        if other is not None and other != target:
            raise BundleError(
                f"{self.spec_path.name}: component name {name!r} is claimed by both "
                f"{other[0].name}#{other[1]} and {target[0].name}#{target[1]}"
            )
        self.names[target] = name
        self.targets[name] = target
        self.pending.append(name)
        return name

    def _component_ref(self, base_path, ref):
        return "#/components/schemas/" + self._assign(resolve_ref_path(base_path, ref))

    def _rewrite(self, node, base_path):
        """Copy `node`, repointing every reference at the bundle's components."""
        if isinstance(node, dict):
            out = {}
            for key, value in node.items():
                if key == "$ref" and isinstance(value, str):
                    out[key] = self._component_ref(base_path, value)
                elif key == "discriminator" and isinstance(value, dict):
                    out[key] = self._rewrite_discriminator(value, base_path)
                else:
                    out[key] = self._rewrite(value, base_path)
            return out
        if isinstance(node, list):
            return [self._rewrite(value, base_path) for value in node]
        return node

    def _rewrite_discriminator(self, discriminator, base_path):
        out = dict(discriminator)
        mapping = discriminator.get("mapping")
        if isinstance(mapping, dict):
            out["mapping"] = {
                tag: (
                    self._component_ref(base_path, value)
                    if isinstance(value, str)
                    else value
                )
                for tag, value in mapping.items()
            }
        default = discriminator.get("defaultMapping")
        if isinstance(default, str):
            out["defaultMapping"] = self._component_ref(base_path, default)
        return out


def bundle_spec(domain):
    return Bundler(REPO_ROOT / f"openapi-{domain}.json").bundle()


def serialize(obj):
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def cmd_write():
    DIST_DIR.mkdir(exist_ok=True)
    for domain in DOMAINS:
        out = DIST_DIR / f"openapi-{domain}-bundled.json"
        out.write_text(serialize(bundle_spec(domain)))
        print(f"wrote {out.relative_to(REPO_ROOT)}")
    return 0


def cmd_check():
    stale = []
    for domain in DOMAINS:
        out = DIST_DIR / f"openapi-{domain}-bundled.json"
        fresh = serialize(bundle_spec(domain))
        if not out.exists():
            stale.append(f"{out.relative_to(REPO_ROOT)} (missing)")
            continue
        if out.read_text() != fresh:
            stale.append(f"{out.relative_to(REPO_ROOT)} (stale)")
    if stale:
        print("Bundled specs are missing or stale:")
        for s in stale:
            print(f"  {s}")
        print("Run: python scripts/bundle_specs.py")
        return 1
    print(f"OK: {len(DOMAINS)} bundled spec(s) up to date in dist/.")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if dist/ outputs are missing or stale.",
    )
    args = parser.parse_args()
    try:
        return cmd_check() if args.check else cmd_write()
    except BundleError as exc:
        print(f"bundle_specs: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
